-- =============================================================================
-- Summary Service — Data Model (DDL)  [SUPERSEDED — intentionally empty]
-- =============================================================================
-- The summary-service tables (event_outbox, cf_fee_reports,
-- cf_fee_report_status_changes, cf_fee_report_adjustments) are NO LONGER
-- created here.
--
-- They are now owned by the HMS Prisma migrations (single source of truth /
-- single migration pipeline), in:
--   Ycare-HMS/prisma/migrations/20260617091918_add_summary_service_tables/
--
-- Fresh-boot procedure for this dev stack:
--   1. docker compose up                       (init SQL 01/02 only)
--   2. docker exec <hms-app> npm run migrate:deploy   (creates summary tables)
--   3. docker exec <hms-app> npx prisma generate
--
-- The summary-service does NOT run migrations and no longer uses
-- `prisma db push`; its prisma/schema.prisma is a read-model that must stay in
-- sync with the HMS migration above.
-- =============================================================================
